apiVersion: v1beta1
kind: ApplianceConfig
metadata:
  name: grout-on-sno-appliance
ocpRelease:
  version: 4.19
  channel: stable
  cpuArchitecture: x86_64

# Minimum 150GB, adjust based on your needs
# Add more space if you have many additional images
# diskSizeGB: 200

# Pull secret - will be populated from auth.json or pull-secret.txt
# You need to provide your pull secret for Red Hat registries
pullSecret: {}

# SSH public key for accessing the cluster nodes
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA7XvcW7XtarEoMeyym+/J9P1icspH5ws61Sh8yNKiST christophefontaine@mbp.foobar.space
userCorePass: redhat
stopLocalRegistry: false
additionalImages:
  - name: quay.io/grout/grout:latest
  - name: quay.io/grout/frr:latest
  - name: registry.redhat.io/rhel9/support-tools:latest
operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
    packages:
      - name: cluster-logging
      - name: loki-operator
      - name: elasticsearch-operator
      - name: local-storage-operator
      - name: ocs-operator
      - name: performance-addon-operator
      - name: sriov-network-operator
